In [1]:
#Importamos laslibrerias necesarias, la base datos y los modelos necesarios
import numpy as np
import sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split


In [6]:
#cargo en esta variable los datos
iris=load_iris()


In [7]:
#Averiguo q tipo de dato es, bunch es una especie de diccionario
type (iris)

sklearn.utils.Bunch

In [8]:
#descubro que tipo de datos vienen
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [9]:
#Aqui nos muestra la matriz y corresponde a los datos de la linea de arriba
#cada renglon es un flor cada columna es una medición
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
#target es igual al Y de algebra o calculo, es decir es el elemento q nosotros deseamos calcular
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
#Como es en python se arranca de cero entonces 0=seteso, 1=versicolor y 2=virginica
#fijense que la data se convierte en numero y esa es una buena practica
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
#nos muestras mas detalles de las lista o atributos
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
#separamos la data en test y trainig, es importante usar datos para entrenar y guardase unos para validar
X_train,X_test,y_train,y_test=train_test_split(iris['data'],iris['target'])

In [15]:
#tenemos 112 flores con 4 mediciones cada uno y te queda asi la matriz
X_train.shape

(112, 4)

In [16]:
y_train.shape


(112,)

In [18]:
#le metemos el metodo de vecinos cercanos
from sklearn.neighbors import KNeighborsClassifier

In [22]:
#el programador define 7 que es el valor de cuantos puntos estan alrededor suyo
knn=KNeighborsClassifier(n_neighbors=7)

In [23]:
#fit función que sirve para enterenar
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=7, p=2,
           weights='uniform')

In [24]:
#score funcion sirve para saber que tambien aprendio el modelo
knn.score(X_test,y_test)

0.9736842105263158

In [26]:
#ahora yo meto valores y me tiene que predecir un valor
#el valor 1 significa queesa medición pertenece a una flor versicolor
knn.predict([[1.2,3.4,5.6,1.1]])

array([1])